### ISSUE TITLE
Make x-token in client optional

### ISSUE THREAD

**Issue by fanatid** [rpcpool/solana-geyser-grpc#68]
We do not need `x-token` if we want to run a client connected to a local test validator. If I miss `--x-token` I get an error:
```
$ cargo-fmt && cargo build --bin client && ./target/debug/client --slots
   Compiling solana-geyser-grpc-client v0.5.2+solana.1.14.15 (/home/kirill/projects/solana-accountsdb-grpc/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 10.43s
Error: XToken: 
Error: XToken("")
```

**Comment by shuimuliang** [comment]
if x-token is empty, will show a warning message.
if x-token is not empty, will check XTOKEN_LENGTH == 28.

is that ok?
